from PySide6.QtWidgets import QWidget, QVBoxLayout, QListWidget, QLabel, QListWidgetItem
from PySide6.QtCore import Qt

class TaskFeedWidget(QWidget):
    """Displays a live feed of autonomous tasks generated by the system."""
    def __init__(self):
        super().__init__()
        layout = QVBoxLayout(self)
        layout.addWidget(QLabel("Autonomous Task Feed"))

        self.task_list = QListWidget()
        layout.addWidget(self.task_list)

    def add_task(self, task: dict):
        item = QListWidgetItem(f"[{task['priority']}] {task['title']}")
        if task['priority'] > 80:
            item.setForeground(Qt.red)
        self.task_list.insertItem(0, item)
