from enum import Enum, auto

class BootstrapPhase(Enum):
    VALIDATE_ENVIRONMENT = auto()
    INITIALIZE_STORAGE = auto()
    VALIDATE_RUNTIME_PATHS = auto()
    LOAD_ECOSYSTEM_REGISTRY = auto()
    INITIALIZE_GOVERNANCE = auto()
    INITIALIZE_MEMORY_SYSTEMS = auto()
    INITIALIZE_PROVIDERS = auto()
    INITIALIZE_FEDERATION = auto()
    INITIALIZE_RUNTIME_KERNEL = auto()
    INITIALIZE_REALTIME_LAYER = auto()
    INITIALIZE_COCKPIT_BRIDGE = auto()
    VALIDATE_HEALTH = auto()
    EXPOSE_RUNTIME_STATE = auto()

BOOTSTRAP_ORDER = [
    BootstrapPhase.VALIDATE_ENVIRONMENT,
    BootstrapPhase.INITIALIZE_STORAGE,
    BootstrapPhase.VALIDATE_RUNTIME_PATHS,
    BootstrapPhase.LOAD_ECOSYSTEM_REGISTRY,
    BootstrapPhase.INITIALIZE_GOVERNANCE,
    BootstrapPhase.INITIALIZE_MEMORY_SYSTEMS,
    BootstrapPhase.INITIALIZE_PROVIDERS,
    BootstrapPhase.INITIALIZE_FEDERATION,
    BootstrapPhase.INITIALIZE_RUNTIME_KERNEL,
    BootstrapPhase.INITIALIZE_REALTIME_LAYER,
    BootstrapPhase.INITIALIZE_COCKPIT_BRIDGE,
    BootstrapPhase.VALIDATE_HEALTH,
    BootstrapPhase.EXPOSE_RUNTIME_STATE,
]
